image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    init: |
      npm install
      npx playwright install
    command: echo "Ready to run tests with LambdaTest!"

ports:
  - port: 9323
    onOpen: ignore

vscode:
  extensions:
    - ms-playwright.playwright

